from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('provider','0001_initial')]
    operations = [
        migrations.CreateModel(name='WorkingHour', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('weekday', models.PositiveSmallIntegerField(choices=[(0,'Monday'),(1,'Tuesday'),(2,'Wednesday'),(3,'Thursday'),(4,'Friday'),(5,'Saturday'),(6,'Sunday')])),('start_time', models.TimeField()),('end_time', models.TimeField()),('is_active', models.BooleanField(default=True)),('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='provider.provider'))], options={'ordering': ('weekday','start_time'), 'unique_together': {('provider','weekday','start_time','end_time')}}),
        migrations.CreateModel(name='SpecialWorkingHour', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('date', models.DateField()),('start_time', models.TimeField(blank=True, null=True)),('end_time', models.TimeField(blank=True, null=True)),('is_available', models.BooleanField(default=True)),('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_working_hours', to='provider.provider'))], options={'ordering': ('date','start_time')}),
        migrations.CreateModel(name='Appointment', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('date', models.DateField()),('start_time', models.TimeField()),('end_time', models.TimeField()),('status', models.CharField(choices=[('pending','Pending'),('confirmed','Confirmed'),('cancelled','Cancelled'),('completed','Completed')], default='pending', max_length=20)),('deposit_paid', models.BooleanField(default=False)),('notes', models.TextField(blank=True)),('created_at', models.DateTimeField(auto_now_add=True)),('updated_at', models.DateTimeField(auto_now=True)),('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='provider.provider')),('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='provider.service'))], options={'ordering': ('date','start_time'), 'indexes': [models.Index(fields=['provider','date','start_time','end_time','status'], name='appointmen_provider_8d755e_idx')]}),
    ]
