version = 1

[[analyzers]]
name = "python"
enabled = true

[analyzers.python]
runtime_version = "3.11"  # یا ورژن پایتونی که استفاده می‌کنی
dependencies = ["pip", "setuptools", "wheel"]

[[analyzers]]
name = "docker"
enabled = true
