version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgresrxm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: k7KcvHQsfeZIC5b6Lsnx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  staticfiles:
  media:
