# Generated by Django 5.1.15 on 2026-06-28
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('subscription', '0001_initial')]
    operations = [
        migrations.AddField(model_name='subscription', name='auto_renew', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='subscription', name='renewal_price_snapshot', field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
    ]
