# Generated by Django 5.2.8 on 2026-07-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_auto_renew_and_renewal_price_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='can_have_gallery',
            field=models.BooleanField(default=False, verbose_name='گالری تصاویر'),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_show_on_homepage',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اول شهر'),
        ),
        migrations.AddField(
            model_name='plan',
            name='can_show_portfolio',
            field=models.BooleanField(default=False, verbose_name='نمایش نمونه کارها'),
        ),
    ]
