# Generated by Django 5.1.15 on 2026-06-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="appointment",
            new_name="reservation_provide_a42388_idx",
            old_name="reserv_prov_date_idx",
        ),
    ]
