# Generated by Django 5.2.16 on 2026-07-21 12:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='✨', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service categories',
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Public booking URL slug', max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('city', models.CharField(db_index=True, default='تهران', max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='providers/avatars/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='providers/covers/')),
                ('theme_color', models.CharField(default='#ec4899', max_length=20)),
                ('background_color', models.CharField(default='#fff7fb', max_length=20)),
                ('accent_color', models.CharField(default='#111827', max_length=20)),
                ('typography', models.CharField(choices=[('sans', 'Sans'), ('serif', 'Serif'), ('rounded', 'Rounded')], default='sans', max_length=20)),
                ('font_family', models.CharField(choices=[('mikhak', 'میکاک (Mikhak)'), ('lalezar', 'لاله\u200cزار (Lalezar)'), ('razan', 'رازان (Razan)'), ('mfsadu', 'ام\u200cاف\u200cسادو (MFSADU)'), ('vazir', 'وزیر (Vazir)'), ('dirooz', 'دیروز (Dirooz)'), ('ravi', 'راوی (Ravi)')], default='mikhak', max_length=30)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('instagram', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('google_map_url', models.URLField(blank=True)),
                ('buffer_minutes', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='provider.provider')),
            ],
            options={
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percent', models.PositiveSmallIntegerField(default=0)),
                ('discount_starts_at', models.DateTimeField(blank=True, null=True)),
                ('discount_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='provider.productcategory')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('before_after', 'Before / After')], default='image', max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='gallery/before_after/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='provider.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('suggested_duration', models.PositiveIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='provider.servicecategory')),
            ],
            options={
                'ordering': ('category__sort_order', 'category__name', 'name'),
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='provider.provider')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_services', to='provider.servicetemplate')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
