# Generated by Django 5.1.15 on 2026-06-28 14:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="✨", max_length=20)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_categories/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Service categories",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="provider",
            name="city",
            field=models.CharField(db_index=True, default="تهران", max_length=80),
        ),
        migrations.AlterField(
            model_name="provider",
            name="slug",
            field=models.SlugField(
                help_text="Public booking URL slug",
                max_length=80,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
        migrations.CreateModel(
            name="ServiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("suggested_duration", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="provider.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ("category__sort_order", "category__name", "name"),
                "unique_together": {("category", "name")},
            },
        ),
        migrations.AddField(
            model_name="service",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provider_services",
                to="provider.servicetemplate",
            ),
        ),
    ]
