# Generated by Django 5.2.8 on 2026-07-01 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_servicecategory_provider_city_alter_provider_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='slug',
            field=models.SlugField(help_text='Public booking URL slug', max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
