# Generated by Django 5.2.8 on 2026-07-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_alter_provider_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='font_family',
            field=models.CharField(choices=[('mikhak', 'میکاک (Mikhak)'), ('tahamtan', 'تهمتن (Tahamtan)'), ('lalezar', 'لاله\u200cزار (Lalezar)'), ('javan', 'ژوان (Javan)'), ('azar_germi', 'آذرگرمی (AzarGermi)'), ('katibeh', 'کتیبه (Katibeh)'), ('razan', 'رازان (Razan)'), ('mfsadu', 'ام\u200cاف\u200cسادو (MFSADU)'), ('khatoon', 'خاتون (Khatoon)'), ('ahang_pro', 'آهنگ پرو (Ahange Pro)')], default='mikhak', max_length=30),
        ),
    ]
