# Generated by Django 5.2.8 on 2026-07-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_provider_font_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='font_family',
            field=models.CharField(choices=[('mikhak', 'میکاک (Mikhak)'), ('lalezar', 'لاله\u200cزار (Lalezar)'), ('razan', 'رازان (Razan)'), ('mfsadu', 'ام\u200cاف\u200cسادو (MFSADU)'), ('vazir', 'وزیر (Vazir)'), ('dirooz', 'دیروز (Dirooz)'), ('ravi', 'راوی (Ravi)')], default='mikhak', max_length=30),
        ),
    ]
