# Generated by Django 5.2.16 on 2026-07-21 12:01

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('placement_code', models.CharField(choices=[('header_top', 'بالای هدر'), ('header_bottom', 'زیر هدر'), ('sidebar_top', 'ابتدای سایدبار'), ('sidebar_sticky', 'سایدبار چسبان'), ('in_article', 'داخل مقاله'), ('before_related', 'قبل از مطالب مرتبط'), ('before_comments', 'قبل از نظرات'), ('footer_mobile', 'بنر پایین موبایل'), ('popup', 'پاپ\u200cآپ'), ('native_product', 'محصول داخل مقاله'), ('sponsored_box', 'باکس اسپانسر')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'جایگاه تبلیغات',
                'verbose_name_plural': 'جایگاه\u200cهای تبلیغات',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای بلاگ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_desktop', models.ImageField(upload_to='ads/desktop/%Y/%m/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='ads/mobile/%Y/%m/')),
                ('link_url', models.URLField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='blog.adplacement')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصه مقاله')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('html', 2), ('image', 3), ('quote', 4), ('list', 6), ('colored_text', 9), ('table', 13), ('button', 17), ('alert', 19), ('divider', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code', 'label': 'HTML سفارشی'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote'}), 5: ('wagtail.blocks.CharBlock', (), {'icon': 'list'}), 6: ('wagtail.blocks.ListBlock', (5,), {'icon': 'list'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('red', 'قرمز'), ('blue', 'آبی'), ('green', 'سبز'), ('yellow', 'زرد'), ('purple', 'بنفش'), ('pink', 'صورتی'), ('orange', 'نارنجی'), ('gray', 'خاکستری'), ('black', 'مشکی')], 'icon': 'color'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'بدون پس\u200cزمینه'), ('red', 'قرمز'), ('blue', 'آبی'), ('green', 'سبز'), ('yellow', 'زرد'), ('purple', 'بنفش'), ('pink', 'صورتی'), ('orange', 'نارنجی'), ('gray', 'خاکستری'), ('light', 'روشن')], 'icon': 'color', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 1), ('color', 7), ('background_color', 8)]], {'icon': 'color'}), 10: ('wagtail.blocks.CharBlock', (), {'icon': 'table'}), 11: ('wagtail.blocks.StreamBlock', [[('cell', 10)]], {'icon': 'table'}), 12: ('wagtail.blocks.StreamBlock', [[('row', 11)]], {'icon': 'table'}), 13: ('wagtail.blocks.StructBlock', [[('rows', 12)]], {'icon': 'table'}), 14: ('wagtail.blocks.CharBlock', (), {'icon': 'title'}), 15: ('wagtail.blocks.URLBlock', (), {'icon': 'link'}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'اصلی'), ('secondary', 'ثانویه'), ('outline', 'بی\u200cحاشیه')], 'icon': 'color'}), 17: ('wagtail.blocks.StructBlock', [[('text', 14), ('link', 15), ('style', 16)]], {'icon': 'link'}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'اطلاعات'), ('warning', 'هشدار'), ('success', 'موفقیت'), ('error', 'خطا')], 'icon': 'warning'}), 19: ('wagtail.blocks.StructBlock', [[('text', 1), ('type', 18)]], {'icon': 'warning'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('solid', 'توپر'), ('dashed', 'خط\u200cچین'), ('dotted', 'نقطه\u200cچین')], 'icon': 'separator'}), 21: ('wagtail.blocks.StructBlock', [[('style', 20)]], {'icon': 'separator'})}, verbose_name='محتوای مقاله')),
                ('categories', models.ManyToManyField(blank=True, related_name='blog_pages', to='blog.blogcategory', verbose_name='دسته\u200cبندی\u200cها')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='تصویر اصلی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوای نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment', verbose_name='پاسخ به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpage', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نظر بلاگ',
                'verbose_name_plural': 'نظرات بلاگ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPageTag', to='taggit.Tag', verbose_name='برچسب\u200cها'),
        ),
    ]
