# Generated by Django 6.0.6 on 2026-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='excerpt',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
