# Generated by Django 5.2.8 on 2026-07-11 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_excerpt_alter_blog_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام جایگاه')),
                ('slug', models.SlugField(unique=True)),
                ('placement_code', models.CharField(choices=[('header_top', 'Header Top - بالای هدر'), ('header_bottom', 'Header Bottom - زیر منوی اصلی'), ('sidebar_top', 'Sidebar Top - ابتدای سایدبار'), ('sidebar_sticky', 'Sidebar Sticky - سایدبار چسبان'), ('in_article', 'In Article - داخل مقاله'), ('before_related', 'Before Related - قبل از مطالب مرتبط'), ('before_comments', 'Before Comments - قبل از نظرات'), ('footer_mobile', 'Footer Mobile - بنر پایین موبایل'), ('popup', 'Popup - پاپ\u200cآپ'), ('native_product', 'Native Product - محصول داخل مقاله'), ('sponsored_box', 'Sponsored Box - باکس اسپانسر')], max_length=50, unique=True, verbose_name='کد جایگاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'جایگاه تبلیغات',
                'verbose_name_plural': 'جایگاه\u200cهای تبلیغات',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(blank=True, help_text='خلاصه مقاله (اختیاری - در صورت خالی بودن خودکار تولید می\u200cشود)', null=True),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تبلیغ')),
                ('image_desktop', models.ImageField(upload_to='ads/desktop/%Y/%m/', verbose_name='تصویر دسکتاپ')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='ads/mobile/%Y/%m/', verbose_name='تصویر موبایل')),
                ('link_url', models.URLField(blank=True, verbose_name='لینک مقصد')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('priority', models.IntegerField(default=0, help_text='هرچه عدد بزرگتر اولویت بیشتر', verbose_name='اولویت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('impression_count', models.IntegerField(default=0, verbose_name='تعداد نمایش')),
                ('click_count', models.IntegerField(default=0, verbose_name='تعداد کلیک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='blog.adplacement', verbose_name='جایگاه')),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
