# Generated by Django 6.0.7 on 2026-07-18 22:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcategory_remove_blog_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='custom_html',
            field=models.TextField(blank=True, help_text='برای استایل\u200cهای پیشرفته مثل رنگ، جدول، چیدمان تصاویر کنار هم از این فیلد استفاده کنید', verbose_name='HTML سفارشی (برای رنگ، جدول، چیدمان پیشرفته)'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='متن مقاله (ادیتور ساده)', features=['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'ol', 'ul', 'hr', 'image', 'document-link', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'embed']),
        ),
    ]
