# Generated by Django 6.0.7 on 2026-07-19 16:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogpage_custom_html_blogpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='content',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('html', 2), ('image', 3), ('quote', 4), ('list', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'ul', 'hr', 'image', 'document-link', 'code', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'embed', 'color'], 'icon': 'pilcrow'}), 2: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code', 'label': 'HTML سفارشی'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote'}), 5: ('wagtail.blocks.CharBlock', (), {'icon': 'list'}), 6: ('wagtail.blocks.ListBlock', (5,), {'icon': 'list'})}, verbose_name='محتوای مقاله'),
        ),
    ]
