# Generated by Django 6.0.7 on 2026-07-19 16:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogpage_content_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('html', 2), ('image', 3), ('quote', 4), ('list', 6), ('colored_text', 9), ('table', 13), ('button', 17), ('alert', 19), ('divider', 21)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 2: ('wagtail.blocks.RawHTMLBlock', (), {'icon': 'code', 'label': 'HTML سفارشی'}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image'}), 4: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote'}), 5: ('wagtail.blocks.CharBlock', (), {'icon': 'list'}), 6: ('wagtail.blocks.ListBlock', (5,), {'icon': 'list'}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('red', 'قرمز'), ('blue', 'آبی'), ('green', 'سبز'), ('yellow', 'زرد'), ('purple', 'بنفش'), ('pink', 'صورتی'), ('orange', 'نارنجی'), ('gray', 'خاکستری'), ('black', 'مشکی')], 'icon': 'color'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('', 'بدون پس\u200cزمینه'), ('red', 'قرمز'), ('blue', 'آبی'), ('green', 'سبز'), ('yellow', 'زرد'), ('purple', 'بنفش'), ('pink', 'صورتی'), ('orange', 'نارنجی'), ('gray', 'خاکستری'), ('light', 'روشن')], 'icon': 'color', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('text', 1), ('color', 7), ('background_color', 8)]], {'icon': 'color'}), 10: ('wagtail.blocks.CharBlock', (), {'icon': 'table'}), 11: ('wagtail.blocks.StreamBlock', [[('cell', 10)]], {'icon': 'table'}), 12: ('wagtail.blocks.StreamBlock', [[('row', 11)]], {'icon': 'table'}), 13: ('wagtail.blocks.StructBlock', [[('rows', 12)]], {'icon': 'table'}), 14: ('wagtail.blocks.CharBlock', (), {'icon': 'title'}), 15: ('wagtail.blocks.URLBlock', (), {'icon': 'link'}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'اصلی'), ('secondary', 'ثانویه'), ('outline', 'بی\u200cحاشیه')], 'icon': 'color'}), 17: ('wagtail.blocks.StructBlock', [[('text', 14), ('link', 15), ('style', 16)]], {'icon': 'link'}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('info', 'اطلاعات'), ('warning', 'هشدار'), ('success', 'موفقیت'), ('error', 'خطا')], 'icon': 'warning'}), 19: ('wagtail.blocks.StructBlock', [[('text', 1), ('type', 18)]], {'icon': 'warning'}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('solid', 'توپر'), ('dashed', 'خط\u200cچین'), ('dotted', 'نقطه\u200cچین')], 'icon': 'separator'}), 21: ('wagtail.blocks.StructBlock', [[('style', 20)]], {'icon': 'separator'})}, verbose_name='محتوای مقاله'),
        ),
    ]
